### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jngls** [btrepp/rust-midi-stomp#2]
Hey @btrepp, I'm making a bluepill midi controller with a few faders and I wanted to use your project as a reference since you've got further than me. The main part I'm looking to borrow is structural - moving over to RTIC, as I'm bumping up against strange USB errors and I think I need to start by making my code more interrupt driven. However, I noticed there's no license file in this project. Are you happy for me to borrow chunks of code here and there? I'm looking to release my project open source under MIT license in the future.

**Comment by btrepp** [comment]
MIT License added :). 

Also note there was some upstream libraries which others now maintain, so check them out, they may have fixed some of your issues.

I do recall timing being very significant on different OS's (eg some you need to be tight, some are more flexible). Wireshark (in usb capture mode) will be very helpful in figuring out weird missing signals or things being ignored.

**Comment by btrepp** [comment]
Also please send me a link when you have built your project. It sounds very cool and I would love to see it when it progresses!

**Comment by jngls** [comment]
Yeah I will share for sure. I'm just de-risking various bits of firmware at this stage, getting through the USB midi side is my current focus, then I'm moving onto TRS midi. After that a few simple things like WS2812 lighting and encoder input. Then I'll move onto the prototype pcb and the fun can begin. I've already got extremely stable denoised and locking fader inputs, maybe overkill for a free controller firmware actually, but I care about the details.

If it's cool with you, I might add you to my repo in the next few weeks if you're willing to code review the USB midi side. Completely optional and no expectations.

**Comment by jngls** [comment]
Thanks for the MIT!

**Comment by jngls** [comment]
Actually never mind, it was more straightforward than it looked at first. Got Midi USB working with RTIC! Cheers!
